# 1. Give your workflow a name
name: Deploy Vite React App

# 2. Define the trigger
on:
  push:
    branches:
      - main

# 3. Define the job
jobs:
  build-and-deploy:
    # 4. Specify the runner environment
    runs-on: ubuntu-latest

    # 5. List the steps to execute
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "dist/*"
        target: "/var/www/react-app"
        strip_components: 1